# Generated by Django 4.1.3 on 2022-11-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(max_length=200)),
                ('auth_key', models.CharField(max_length=200, verbose_name="Clau d'autorització")),
            ],
        ),
        migrations.CreateModel(
            name='Espai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_aula', models.CharField(max_length=10, verbose_name="Codi d'aula")),
                ('id_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Franja_horaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinici', models.TimeField(verbose_name="Hora d'inici")),
                ('hfinal', models.TimeField(verbose_name="Hora d'acabament")),
                ('es_pati', models.BooleanField(verbose_name="És hora d'esplai?")),
                ('id_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup', models.CharField(max_length=10)),
                ('id_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('id_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=200, verbose_name='Matèria')),
                ('id_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Horari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_setmana', models.CharField(max_length=2, verbose_name='Dia de la setmana')),
                ('es_guardia', models.BooleanField(verbose_name='És una guàrdia?')),
                ('id_espai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.espai')),
                ('id_grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.grup')),
                ('id_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.franja_horaria')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.materia')),
                ('id_usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.usuari')),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('feina', models.CharField(max_length=200, verbose_name='Feina deixada pel professor titular')),
                ('id_horari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.horari')),
                ('id_substitut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.usuari')),
            ],
        ),
        migrations.CreateModel(
            name='Absencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name="Data d'inici")),
                ('data_fi', models.DateField(verbose_name="Data d'acabament")),
                ('hora_ini', models.TimeField(verbose_name="Hora d'inici")),
                ('hora_fi', models.TimeField(verbose_name="Hora d'acabament")),
                ('dia_complet', models.BooleanField(verbose_name='És absència de tota la jornada?')),
                ('extraescolar', models.BooleanField(verbose_name='Es deu a una activitat extraescolar?')),
                ('justificada', models.BooleanField(verbose_name="S'ha justificat l'absència?")),
                ('id_horari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absencies.horari')),
            ],
        ),
    ]
