# Generated by Django 4.1.3 on 2022-11-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absencia',
            old_name='id_horari',
            new_name='horari',
        ),
        migrations.RenameField(
            model_name='espai',
            old_name='id_centre',
            new_name='centre',
        ),
        migrations.RenameField(
            model_name='franja_horaria',
            old_name='id_centre',
            new_name='centre',
        ),
        migrations.RenameField(
            model_name='grup',
            old_name='id_centre',
            new_name='centre',
        ),
        migrations.RenameField(
            model_name='guardia',
            old_name='id_horari',
            new_name='horari',
        ),
        migrations.RenameField(
            model_name='guardia',
            old_name='id_substitut',
            new_name='substitut',
        ),
        migrations.RenameField(
            model_name='horari',
            old_name='id_espai',
            new_name='espai',
        ),
        migrations.RenameField(
            model_name='horari',
            old_name='id_grup',
            new_name='grup',
        ),
        migrations.RenameField(
            model_name='horari',
            old_name='id_hora',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='horari',
            old_name='id_materia',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='horari',
            old_name='id_usuari',
            new_name='usuari',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='id_centre',
            new_name='centre',
        ),
        migrations.RenameField(
            model_name='usuari',
            old_name='id_centre',
            new_name='centre',
        ),
    ]
