# Generated by Django 4.1.3 on 2022-11-30 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0003_alter_absencia_data_fi_alter_absencia_hora_fi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horari',
            name='dia_setmana',
        ),
        migrations.AddField(
            model_name='franja_horaria',
            name='dia_setmana',
            field=models.CharField(default='DI', max_length=2, verbose_name='Dia de la setmana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardia',
            name='dia_setmana',
            field=models.CharField(default='DI', max_length=2, verbose_name='Dia de la setmana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absencia',
            name='data_fi',
            field=models.DateField(blank=True, null=True, verbose_name="Data d'acabament"),
        ),
        migrations.AlterField(
            model_name='absencia',
            name='hora_fi',
            field=models.TimeField(blank=True, null=True, verbose_name="Hora d'acabament"),
        ),
        migrations.AlterField(
            model_name='absencia',
            name='hora_ini',
            field=models.TimeField(blank=True, null=True, verbose_name="Hora d'inici"),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='substitut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='absencies.usuari'),
        ),
        migrations.AlterField(
            model_name='horari',
            name='espai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='absencies.espai'),
        ),
        migrations.AlterField(
            model_name='horari',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='absencies.grup'),
        ),
        migrations.AlterField(
            model_name='horari',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='absencies.materia'),
        ),
    ]
