# Generated by Django 4.1.3 on 2022-11-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0004_remove_horari_dia_setmana_franja_horaria_dia_setmana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardia',
            name='dia_setmana',
        ),
    ]
