# Generated by Django 4.1.3 on 2022-12-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0005_remove_guardia_dia_setmana'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='absencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='absencies.absencia'),
            preserve_default=False,
        ),
    ]
