# Generated by Django 4.1.3 on 2022-12-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0006_guardia_absencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencia',
            name='horari',
        ),
        migrations.AddField(
            model_name='absencia',
            name='usuari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='absencies.usuari'),
        ),
    ]
