# Generated by Django 4.1.3 on 2022-12-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0007_remove_absencia_horari_absencia_usuari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencia',
            name='usuari',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='absencies.usuari'),
            preserve_default=False,
        ),
    ]
