# Generated by Django 4.1.3 on 2022-12-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0008_alter_absencia_usuari'),
    ]

    operations = [
        migrations.AddField(
            model_name='franja_horaria',
            name='ndia_setmana',
            field=models.IntegerField(default=0),
        ),
    ]
