# Generated by Django 4.1.3 on 2022-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0009_franja_horaria_ndia_setmana'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuari',
            name='password',
            field=models.CharField(default='1234', max_length=200),
            preserve_default=False,
        ),
    ]
