# Generated by Django 4.1.3 on 2022-12-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absencies', '0010_usuari_email_usuari_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='auth_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuari',
            name='login',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='horari',
            name='espai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='absencies.espai'),
        ),
        migrations.AlterField(
            model_name='horari',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='absencies.grup'),
        ),
        migrations.AlterField(
            model_name='horari',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='absencies.materia'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='absencies.centre'),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usuari',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
